### ISSUE TITLE
config.txt folder 지정 수정요구

### ISSUE THREAD

**Issue by semibank** [kysth0707/LineMaker#1]
현재 관리자계정의 config.txt를 활용
개선요구사항 -: 현재 실행 프로그램 디렉토리에 있는 config.txt를 사용할 수 있도록 검토바람.
일반사용자가 사용할 수 있도록 배포용 실행파일 포함요구함

**Comment by semibank** [comment]
수정 후 커밋 메세지에 Close #1 을 적으면 이슈 자동 종료

**Comment by kysth0707** [comment]
일시적인 오류인 것으로 확인 완료
